'use client'

import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.scss";
import "./typography.scss"
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider, createTheme } from "@mui/material";
import { ToastContainer } from "react-toastify";

const theme = createTheme({
  typography: {
    fontFamily: 'VazirmatnFD',
  },
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
createTheme

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
          <ToastContainer />
              {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
